server {
  listen 80;
  server_name _;

  error_log /var/log/nginx/3qrain.error.log warn;
  
  # 文件上传切片100m，这里限制105m
  client_max_body_size 105m;

  # =========================
  # Admin (Vue dist)
  # =========================
  location = /admin {
        return 301 /admin/;
  }

  location ^~ /admin/ {
    alias /var/www/3qrain/admin/;
    index index.html;
    try_files $uri $uri/ /admin/index.html;
  }

  # =========================
  # API (Hono / Bun)
  # =========================
  location /api/ {
    proxy_pass http://127.0.0.1:3010;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /storage/ {
      proxy_pass http://127.0.0.1:3010;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
  }
  # =========================
  # Web (Nuxt)
  # =========================
  location / {
    proxy_pass http://127.0.0.1:3020;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # =========================
  # gzip (可选优化)
  # =========================
  gzip on;
  gzip_types text/plain application/json application/javascript text/css;
}