services:
  mongo:
    image: mongo:8
    container_name: 3qrain-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: 3qrain
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    name: 3qrain-mongo-data